In [1]:
import numpy as np

In [2]:
import numpy as np

In [3]:
lst = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

arr = np.array(lst)

print(arr * 4)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

min_index = np.argmin(arr)
max_index = np.argmax(arr)

print(min_index)
print(max_index)

print(arr[min_index])
print(arr[max_index])

print(np.min(arr))
print(np.max(arr))

print(arr[arr > 20])

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
6
7
4
50
4
50
[27 31 50 39 35]


In [4]:
matrix = np.array([
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
])

print(matrix.shape)
print("Rows:", matrix.shape[0])
print("Columns:", matrix.shape[1])

print(matrix[:, 2])
print(matrix[1, :])

print(matrix * 2)

print(np.mean(matrix, axis=0))
print(np.mean(matrix))

print(np.max(matrix, axis=1))
print(np.min(matrix, axis=0))

flat = matrix.flatten()
print(flat)
print(flat.shape)

min_flat_index = np.argmin(matrix)
max_flat_index = np.argmax(matrix)

print(min_flat_index)
print(max_flat_index)

print(np.unravel_index(min_flat_index, matrix.shape))
print(np.unravel_index(max_flat_index, matrix.shape))

print(matrix[matrix > 15])

print(np.sort(matrix, axis=1))

(3, 4)
Rows: 3
Columns: 4
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19]
[ 5 12 14  3]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
(12,)
7
5
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))
[17 21 19]
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [5]:
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

def prime_rows(array):
    keep_rows = []
    for row in array:
        has_prime = False
        for value in row:
            if is_prime(value):
                has_prime = True
        if has_prime:
            keep_rows.append(row)
    return np.array(keep_rows)

print(prime_rows(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [6]:
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[0::2, 0::2] = 1
    board[1::2, 1::2] = 1
    return board

print(checkerboard())


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [7]:
def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[0::2, 1::2] = 1
    board[1::2, 0::2] = 1
    return board

print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
def expansion(words, spaces):
    gap = " " * spaces
    expanded = []
    for word in words:
        expanded.append(gap.join(list(word)))
    return np.array(expanded)

universe = np.array(["galaxy", "clusters"])
print(expansion(universe, 1))
print(expansion(universe, 2))

['g a l a x y' 'c l u s t e r s']
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [9]:
def secondDimmest(stars):
    result = []
    for row in stars:
        sorted_row = np.sort(row)
        result.append(sorted_row[-2])
    return np.array(result)

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))

print(stars)
print(secondDimmest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
